repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [ --py311-plus ]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.25.0
    hooks:
      - id: django-upgrade
        language_version: python3.12
        args: [ --target-version, "5.2" ]
  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: Check for uncreated migrations
        entry: make managepy arguments="makemigrations --check --dry-run"
        files: "models\\.py$"
        stages: [ commit ]
        require_serial: true
  - repo: local
    hooks:
      - id: messages-check
        language: system
        name: Compile the messages
        entry: make managepy arguments="compilemessages -l pl"
        files: ".+\\.po$"
        stages: [ commit ]
        require_serial: true
