[project]
name = "olxscraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.1.1",
    "pre-commit>=3.8.0",
]
