# Generated by Django 4.2.2 on 2023-07-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flats", "0002_category_search"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="flat",
            options={"verbose_name": "flat", "verbose_name_plural": "flats"},
        ),
        migrations.AlterModelOptions(
            name="search",
            options={"verbose_name": "search", "verbose_name_plural": "searches"},
        ),
        migrations.AddField(
            model_name="search",
            name="finished",
            field=models.BooleanField(default=False),
        ),
    ]
