services:
  server:
    image: jkoldun/olxscraper:latest
    entrypoint: ./docker/entrypoints/server-entrypoint.sh
    env_file: .env.prod
    ports:
      - "80:8000"
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "15672:15672"
    env_file: .env.prod
  worker:
    image: jkoldun/olxscraper:latest
    entrypoint: ./docker/entrypoints/worker-entrypoint.sh
    env_file: .env.prod
    depends_on:
      - rabbitmq
  beat:
    image: jkoldun/olxscraper:latest
    entrypoint: ./docker/entrypoints/beat-entrypoint.sh
    env_file: .env.prod
    depends_on:
      - rabbitmq
