# Generated by Django 4.2.2 on 2023-07-01 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flats", "0002_categories"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categories",
            new_name="Category",
        ),
    ]
