# Generated by Django 4.2.2 on 2023-07-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flats", "0003_rename_categories_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="search",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="url",
            field=models.CharField(max_length=500),
        ),
    ]
