# Generated by Django 4.2.2 on 2023-07-02 08:32

from django.db import migrations, models
import django.db.models.deletion
import flats.validators


class Migration(migrations.Migration):
    dependencies = [
        ("flats", "0004_category_search_alter_category_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flat",
            name="created",
        ),
        migrations.RemoveField(
            model_name="flat",
            name="type",
        ),
        migrations.AddField(
            model_name="flat",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="flats.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="price",
            field=models.PositiveSmallIntegerField(
                validators=[
                    flats.validators.validate_url_has_brackets,
                    flats.validators.validate_url_page,
                ]
            ),
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_search",
                        to="flats.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flat",
            name="search",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="flats.search",
            ),
            preserve_default=False,
        ),
    ]
