x-default: &default
  env_file: .env
  image: jkoldun/olxscraper:latest

services:

  web:
    <<: *default
    command: uvicorn olxscraper.asgi:application --host 0.0.0.0 --port 8000
    ports:
      - "80:8000"
    volumes:
      - staticfiles:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

  migration:
    <<: *default
    command: python manage.py migrate
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  static:
    <<: *default
    command: python manage.py collectstatic --noinput
    volumes:
      - staticfiles:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  db:
    image: postgres:17-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_NAME:-postgres}"]
      interval: 10s
      timeout: 5s

  rabbitmq:
    image: rabbitmq:3-management
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  worker:
    <<: *default
    command: celery -A olxscraper worker -l INFO
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

  beat:
    <<: *default
    command: celery -A olxscraper beat -l INFO
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

volumes:
  pgdata:
  staticfiles:
