# Generated by Django 5.2.4 on 2025-08-03 20:23

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(help_text='The URL of the item')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the category, e.g. 'Mobile phones'", max_length=255)),
                ('search_frequency', models.ForeignKey(help_text='How often the search should be performed', on_delete=django.db.models.deletion.PROTECT, to='django_celery_beat.intervalschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Should describe the address of the category, e.g. 'Mobile phones up to $1000'", max_length=255)),
                ('url', models.URLField(help_text="The URL of the category with all the filters applied, e.g. 'https://www.olx.pl/elektronika/telefony-i-smartfony/'")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searches.category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('changes', models.TextField(help_text='The changes that were made to the item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searches.item')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_finished', models.BooleanField(default=False, help_text='Whether the search was finished successfully')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searches.address')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('item', models.ForeignKey(help_text='The item that was found', on_delete=django.db.models.deletion.PROTECT, to='searches.item')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searches.search')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
