# Generated by Django 5.2.4 on 2025-08-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='url',
            field=models.URLField(help_text="The URL of the category with all the filters applied, e.g. 'https://www.olx.pl/elektronika/telefony-i-smartfony/'", max_length=2048),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(help_text='The URL of the item', max_length=2048),
        ),
    ]
