# Generated by Django 5.2.4 on 2025-08-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0002_alter_address_url_alter_item_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='itemupdate',
            options={'verbose_name': 'Item Update', 'verbose_name_plural': 'Item Updates'},
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'Search', 'verbose_name_plural': 'Searches'},
        ),
        migrations.AlterModelOptions(
            name='searchresult',
            options={'verbose_name': 'Search Result', 'verbose_name_plural': 'Search Results'},
        ),
        migrations.AddField(
            model_name='searchresult',
            name='was_found',
            field=models.BooleanField(default=False, help_text='Whether the item was found in this search'),
        ),
    ]
