# Generated by Django 5.2.4 on 2025-08-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0003_alter_address_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='website',
            field=models.CharField(choices=[('OLX', 'OLX'), ('KLEINANZEIGEN', 'KLEINANZEIGEN')], default='OLX', help_text='Which website you want to search', max_length=255),
            preserve_default=False,
        ),
    ]
