# Generated by Django 5.2.4 on 2025-09-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0004_address_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='website',
            field=models.CharField(choices=[('OLX', 'OLX'), ('OTOMOTO', 'OTOMOTO'), ('KLEINANZEIGEN', 'KLEINANZEIGEN')], help_text='Which website you want to search', max_length=255),
        ),
    ]
